# Site settings
title: CMU UCC
tagline: Founded in 2002, UCC is the organization behind all things consulting at Carnegie Mellon.

baseurl: /CMU-UCC

collections:
  initiatives:
    output: true
  projects:
    output: true


# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
