# Site settings
title: CMU Undergraduate Consulting Club
tagline: "Changing the world, one uninspired quote at a time"
url: "cmuucc.com" # The base hostname & protocol for your site. Use it if you need absolute URL's

baseurl: /cmu-ucc

# Social

logo: /img/logo.png
facebook: cmuucc

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
