# Site settings
title: CMU UCC
tagline: "Changing the world, one uninspired quote at a time"
url: "cmuucc.com" # The base hostname & protocol for your site. Use it if you need absolute URL's

baseurl: /CMU-UCC

collections:
  initiatives:
    output: true
  projects:
    output: true


# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
